# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script
      run: python runGetDataPython/getYoutbeData.py
    - name: Commit report
      run: |
           git config --global user.email "huangsoren@gmail.com"
           git config --global user.name "OtakuSoren"
           git add example.csv
           git commit -am "Automated report"
           git push

