name: update_example

on:
  push:
    branches: ['main']

jobs:
  pull-request:
    name: Open PR to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run Python script to create CSV file
        run: python runGetDataPython/build_csv_file.py

      - name: Commit and push changes
        run: |
          git config --local user.email "huangsoren@gmail.com"
          git config --local user.name "OtakuSoren"
          git add example.csv
          git commit -m "Update example.csv"
          git push

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "update_example"
          github_token: ${{ secrets.GITHUB_TOKEN }}
