name: update_example

on:
  push:
    branches: ['main']

jobs:
  pull-request:
    name: updateCSV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - name: Run Python script to create CSV file
        run: python runGetDataPython/getYoutbeData.py

   
